### PR TITLE
Corrected isSubscribed method, added onHost, minor things

### PR DESCRIPTION
**Pull request by mvarendorff**
Created two classes for TwitchAPIConnections. Might (need to) move the requests in Channel over some time.
onHost triggered by a private message by "jtv" with hoster in message body.
Removed deprecation of `#toString()`. Just because it works without doesn't mean one shouldn't and I often get deprecation warnings in my projects because I don't want to do `channel + ""` but rather go for the more easily readable `toString()`. And it is not like the method will be removed any time soon ^^

### CODE REVIEW

**Comment by mvarendorff** [comment]
Will hopefully fix #27 and #30

**Comment by mvarendorff** [comment]
I will leave this here for you @cavariux to look over it so if you have anything to change, feel free to drop me a note or change things ^^

**Comment by mvarendorff** [comment]
Closing because onHost issue. See #30

**Comment by lmariscal** [comment]
Sure, thanks for the help haha, it has exploded the last days. Again thank you ^^

**Pull request closed without merging**
